kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        # name: traefik-ingress-lb
        k8s-app: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - name: traefik-ingress-lb
        image: traefik
        imagePullPolicy: IfNotPresent
        args:
        # - --web
        - --api=true
        # - --kubernetes
        - --providers.kubernetesingress=false
        - --providers.kubernetescrd=false
        - --experimental.kubernetesgateway
        - --providers.kubernetesgateway
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 8080
        # resources:
        #   limits:
        #     cpu: 200m
        #     memory: 30Mi
        #   requests:
        #     cpu: 100m
        #     memory: 20Mi
